"""empty message

Revision ID: c7e3aa136c05
Revises: 2e7888d188bc
Create Date: 2019-07-15 14:07:45.860548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e3aa136c05'
down_revision = '2e7888d188bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'create_time')
    # ### end Alembic commands ###
